### PR TITLE
Implemented google maps, added location centering button

### PR DESCRIPTION
**Pull request by FredericSH**

### CODE REVIEW

**Comment by zuelah** [comment]
Good work.

**Comment by TheBurnerGuy** [comment]
are we still using osmdroid? Or is that a substitute now?

**Comment by zuelah** [comment]
As far as Im aware this is just looking into an alternative right now. Fred was testing out google maps to see what he could do and so far its been good. Lets talk it over on the meeting. I also regret merging it to master as I new realize this should be a separate branch

**Comment by TheBurnerGuy** [comment]
Sounds good.

**Comment by VukR** [comment]
Looks good, one problem I found is that when it asks for geo location permission on my phone and I allow it, it doesn't turn it on, but instead I have manually do it.

**Pull request merged**
